//* This file is part of the MOOSE framework
//* https://www.mooseframework.org
//*
//* All rights reserved, see COPYRIGHT for full restrictions
//* https://github.com/idaholab/moose/blob/master/COPYRIGHT
//*
//* Licensed under LGPL 2.1, please see LICENSE for details
//* https://www.gnu.org/licenses/lgpl-2.1.html

#include "CoarseningIntegralAux.h"
#include "CoarseningIntegralTracker.h"

registerMooseObject("PhaseFieldApp", CoarseningIntegralAux);

template <>
InputParameters
validParams<CoarseningIntegralAux>()
{
  InputParameters params = validParams<AuxKernel>();
  params.addClassDescription(
      "Monitor the correction term generated by a given CoarseningIntegralTracker user object.");
  params.addRequiredParam<UserObjectName>("tracker", "Coarsening integral tracker user object");
  return params;
}

CoarseningIntegralAux::CoarseningIntegralAux(const InputParameters & parameters)
  : AuxKernel(parameters), _tracker(getUserObject<CoarseningIntegralTracker>("tracker"))
{
}

Real
CoarseningIntegralAux::computeValue()
{
  return _tracker.sourceValue(_current_elem);
}
